name: CD Pipeline
on:
  workflow_run:
    workflows: [CI Pipeline]
    types:
        - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [Front-1, Front-2]
    
    steps:
    - name: pull docker image
      run: sudo docker pull $DOCKER_USERNAME/react-hello-world:latest
    - name: delete old docker container
      run: sudo docker rm -f react-hello-world || true
    - name: run docker container
      run: sudo docker run -d -p 3000:3000 --name react-hello-world-container $DOCKER_USERNAME/react-hello-world
      